### ISSUE TITLE
fastqc by default is 4 threads, but really only 1 is being used. 

### ISSUE THREAD

**Issue by mimakaev** [mirnylab/distiller-nf#35] opened 2017-05-22 16:16 UTC

**Comment by sergpolly** [comment] 2017-10-15 02:39
this is user configurable via config files https://github.com/mirnylab/distiller-nf/tree/master/configs

**Comment by golobor** [comment] 2018-12-24 04:52
a duplicate of https://github.com/mirnylab/distiller-nf/issues/120

**Closed by golobor** 2018-12-24 04:52 UTC
