### ISSUE TITLE
chunks of fastq.gz not deleted from work folder upon completion of a job 

### ISSUE THREAD

**Issue by mimakaev** [mirnylab/distiller-nf#33] opened 2017-05-20 18:24 UTC

**Comment by sergpolly** [comment] 2017-10-15 00:35
that's by design I guess ?!

**Comment by golobor** [comment] 2018-05-12 17:00
the new 'cleanup' feature of nextflow can solve this issue - https://github.com/nextflow-io/nextflow/issues/649

**Comment by golobor** [comment] 2018-12-21 07:03
closing as a duplicate of  https://github.com/mirnylab/distiller-nf/issues/31

**Closed by golobor** 2018-12-21 07:03 UTC
