### ISSUE TITLE
parse_runs default is 8 cpus, but is it really?

### ISSUE THREAD

**Issue by mimakaev** [mirnylab/distiller-nf#59] opened 2017-09-15 04:18 UTC
It seems to be that the actual CPU consumption is like 250% pbzip, and 100% python, which is <~ 4 cpus. Maybe change default?

**Comment by sergpolly** [comment] 2017-10-15 02:57
this is user configurable now https://github.com/mirnylab/distiller-nf/tree/master/configs

this is yet to be documented somewhere, but,
in a newest version of `distiller` we have a "master" config [file](https://github.com/mirnylab/distiller-nf/blob/master/nextflow.config), inside of which you can find a section https://github.com/mirnylab/distiller-nf/blob/09a9b41567587384ccb39c76da49f7986f381789/nextflow.config#L12

and inside this section you have a couple of profiles `standard` (name reserved by `nextflow`, would run by default) and `cluster` - these profiles refer to other `.config` [files](https://github.com/mirnylab/distiller-nf/tree/master/configs)  that contain most of the hardware configuration details for each `process` individually.

You can run you `distiller.nf` with `-profile cluster` or `-profile local`(the default) flag to make `nextflow` use one config or the other. We thought it would be a good way to separate execution-related parameters that are platform-dependent  from platform-independent ones (stored in a master-config). This has to be documented of course. Does it all make sense? Would you say it's a confusing way, or documentation would resolve all the issues?

**Comment by golobor** [comment] 2018-12-24 04:52
closing as a duplicate of https://github.com/mirnylab/distiller-nf/issues/120

**Closed by golobor** 2018-12-24 04:52 UTC
