### ISSUE TITLE
Mapping is completed as finished when interrupted

### ISSUE THREAD

**Issue by mimakaev** [mirnylab/distiller-nf#57] opened 2017-09-01 22:11 UTC
If nextflow is restarted while mapping is going, and is later restarted, previous mapping runs are skipped as "stored process", even though they never finished.

**Comment by nvictus** [comment] 2017-09-01 22:21
Do you delete unfinished output files in `intermediates` after a run fails? I noticed that was an issue that would cause it to skip incomplete steps when restarted because the target file exists. Which is fair.

**Comment by mimakaev** [comment] 2017-09-01 22:33
I don't, and it would be unfeasible for a complex job with many chunks etc. 
Shouldn't nextflow automatically mark jobs that were ctrl+c'ed when running as not complete?

**Comment by nvictus** [comment] 2017-09-01 22:49
In snakemake, it won't delete files unless they are explicitly labeled as targets (side effect files stay). Maybe nextflow does the same and some output isn't properly registered as output. @golobor?

**Comment by sergpolly** [comment] 2017-09-05 15:34
this is related to issue #52 . And this is "by design", inherited feature of nextflow for the `storeDirs`, which, according to Paolo, we should get rid of in all of the processes except for getting SRAs.
Nextflow resume much "better" from the `./work` folder contents, and using `storeDirs` prevent it from doing so

**Comment by sergpolly** [comment] 2018-03-11 03:25
`storeDir` behavior have been fixed apparently:
https://github.com/nextflow-io/nextflow/issues/227

also review this to see if it's relevant: https://github.com/nextflow-io/nextflow/issues/592

**Comment by golobor** [comment] 2018-12-12 03:38
ok, @mimakaev , @sergpolly , closing this one?

**Comment by sergpolly** [comment] 2018-12-12 03:44
Agrred

1 issue about storeDirs should be enough: #52

**Comment by golobor** [comment] 2018-12-12 04:20
merging with https://github.com/mirnylab/distiller-nf/issues/52

**Closed by golobor** 2018-12-12 04:20 UTC
